<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class UpazilaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('upazilas')->truncate();
        Schema::enableForeignKeyConstraints();

        $now = now();

        $rows = [
            ['district_id' => 46, 'name' => 'Akkelpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 46, 'name' => 'Joypurhat Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 46, 'name' => 'Kalai',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 46, 'name' => 'Khetlal',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 46, 'name' => 'Panchbibi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 45, 'name' => 'Adamdighi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 45, 'name' => 'Bogra Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 45, 'name' => 'Dhunat',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 45, 'name' => 'Dhupchanchia',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 45, 'name' => 'Gabtali',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 45, 'name' => 'Kahaloo',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 45, 'name' => 'Nandigram',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 45, 'name' => 'Sariakandi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 45, 'name' => 'Shajahanpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 45, 'name' => 'Sherpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 45, 'name' => 'Shibganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 45, 'name' => 'Sonatola',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 47, 'name' => 'Atrai',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 47, 'name' => 'Badalgachhi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 47, 'name' => 'Manda',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 47, 'name' => 'Dhamoirhat',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 47, 'name' => 'Mohadevpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 47, 'name' => 'Naogaon Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 47, 'name' => 'Niamatpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 47, 'name' => 'Patnitala',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 47, 'name' => 'Porsha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 47, 'name' => 'Raninagar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 47, 'name' => 'Sapahar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 48, 'name' => 'Bagatipara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 48, 'name' => 'Baraigram',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 48, 'name' => 'Gurudaspur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 48, 'name' => 'Lalpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 48, 'name' => 'Natore Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 48, 'name' => 'Singra',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 48, 'name' => 'Naldanga',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 49, 'name' => 'Bholahat',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 49, 'name' => 'Gomastapur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 49, 'name' => 'Nachole',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 49, 'name' => 'Nawabganj Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 49, 'name' => 'Shibganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 50, 'name' => 'Ataikula',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 50, 'name' => 'Atgharia',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 50, 'name' => 'Bera',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 50, 'name' => 'Bhangura',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 50, 'name' => 'Chatmohar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 50, 'name' => 'Faridpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 50, 'name' => 'Ishwardi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 50, 'name' => 'Pabna Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 50, 'name' => 'Santhia',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 50, 'name' => 'Sujanagar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 52, 'name' => 'Belkuchi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 52, 'name' => 'Chauhali',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 52, 'name' => 'Kamarkhanda',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 52, 'name' => 'Kazipur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 52, 'name' => 'Raiganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 52, 'name' => 'Shahjadpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 52, 'name' => 'Sirajganj Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 52, 'name' => 'Tarash',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 52, 'name' => 'Ullahpara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 51, 'name' => 'Bagha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 51, 'name' => 'Bagmara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 51, 'name' => 'Charghat',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 51, 'name' => 'Durgapur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 51, 'name' => 'Godagari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 51, 'name' => 'Mohanpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 51, 'name' => 'Paba',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 51, 'name' => 'Puthia',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 51, 'name' => 'Tanore',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 51, 'name' => 'Boalia Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 51, 'name' => 'Matihar Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 51, 'name' => 'Rajpara Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 51, 'name' => 'Shah Mokdum Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 53, 'name' => 'Birampur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 53, 'name' => 'Birganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 53, 'name' => 'Biral',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 53, 'name' => 'Bochaganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 53, 'name' => 'Chirirbandar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 53, 'name' => 'Phulbari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 53, 'name' => 'Ghoraghat',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 53, 'name' => 'Hakimpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 53, 'name' => 'Kaharole',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 53, 'name' => 'Khansama',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 53, 'name' => 'Dinajpur Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 53, 'name' => 'Nawabganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 53, 'name' => 'Parbatipur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 54, 'name' => 'Phulchhari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 54, 'name' => 'Gaibandha Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 54, 'name' => 'Gobindaganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 54, 'name' => 'Palashbari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 54, 'name' => 'Sadullapur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 54, 'name' => 'Sughatta',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 54, 'name' => 'Sundarganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 55, 'name' => 'Bhurungamari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 55, 'name' => 'Char Rajibpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 55, 'name' => 'Chilmari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 55, 'name' => 'Phulbari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 55, 'name' => 'Kurigram Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 55, 'name' => 'Nageshwari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 55, 'name' => 'Rajarhat',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 55, 'name' => 'Raomari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 55, 'name' => 'Ulipur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 56, 'name' => 'Aditmari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 56, 'name' => 'Hatibandha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 56, 'name' => 'Kaliganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 56, 'name' => 'Lalmonirhat Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 56, 'name' => 'Patgram',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 57, 'name' => 'Dimla',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 57, 'name' => 'Domar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 57, 'name' => 'Jaldhaka',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 57, 'name' => 'Kishoreganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 57, 'name' => 'Nilphamari Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 57, 'name' => 'Saidpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 58, 'name' => 'Atwari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 58, 'name' => 'Boda',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 58, 'name' => 'Debiganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 58, 'name' => 'Panchagarh Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 58, 'name' => 'Tetulia',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 59, 'name' => 'Badarganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 59, 'name' => 'Gangachhara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 59, 'name' => 'Kaunia',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 59, 'name' => 'Rangpur Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 59, 'name' => 'Mithapukur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 59, 'name' => 'Pirgachha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 59, 'name' => 'Pirganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 59, 'name' => 'Taraganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 60, 'name' => 'Baliadangi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 60, 'name' => 'Haripur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 60, 'name' => 'Pirganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 60, 'name' => 'Ranisankail',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 60, 'name' => 'Thakurgaon Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 1, 'name' => 'Amtali',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 1, 'name' => 'Bamna',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 1, 'name' => 'Barguna Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 1, 'name' => 'Betagi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 1, 'name' => 'Patharghata',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 1, 'name' => 'Taltoli',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 2, 'name' => 'Agailjhara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 2, 'name' => 'Babuganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 2, 'name' => 'Bakerganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 2, 'name' => 'Banaripara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 2, 'name' => 'Gaurnadi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 2, 'name' => 'Hizla',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 2, 'name' => 'Barisal Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 2, 'name' => 'Mehendiganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 2, 'name' => 'Muladi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 2, 'name' => 'Wazirpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 3, 'name' => 'Bhola Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 3, 'name' => 'Burhanuddin',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 3, 'name' => 'Char Fasson',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 3, 'name' => 'Daulatkhan',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 3, 'name' => 'Lalmohan',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 3, 'name' => 'Manpura',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 3, 'name' => 'Tazumuddin',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 4, 'name' => 'Jhalokati Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 4, 'name' => 'Kathalia',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 4, 'name' => 'Nalchity',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 4, 'name' => 'Rajapur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 5, 'name' => 'Bauphal',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 5, 'name' => 'Dashmina',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 5, 'name' => 'Galachipa',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 5, 'name' => 'Kalapara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 5, 'name' => 'Mirzaganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 5, 'name' => 'Patuakhali Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 5, 'name' => 'Rangabali',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 5, 'name' => 'Dumki',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 6, 'name' => 'Bhandaria',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 6, 'name' => 'Kawkhali',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 6, 'name' => 'Mathbaria',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 6, 'name' => 'Nazirpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 6, 'name' => 'Pirojpur Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 6, 'name' => 'Nesarabad (Swarupkati)',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 6, 'name' => 'Zianagor',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 7, 'name' => 'Ali Kadam',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 7, 'name' => 'Bandarban Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 7, 'name' => 'Lama',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 7, 'name' => 'Naikhongchhari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 7, 'name' => 'Rowangchhari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 7, 'name' => 'Ruma',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 7, 'name' => 'Thanchi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 8, 'name' => 'Akhaura',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 8, 'name' => 'Bancharampur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 8, 'name' => 'Brahmanbaria Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 8, 'name' => 'Kasba',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 8, 'name' => 'Nabinagar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 8, 'name' => 'Nasirnagar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 8, 'name' => 'Sarail',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 8, 'name' => 'Ashuganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 8, 'name' => 'Bijoynagar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 9, 'name' => 'Chandpur Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 9, 'name' => 'Faridganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 9, 'name' => 'Haimchar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 9, 'name' => 'Haziganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 9, 'name' => 'Kachua',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 9, 'name' => 'Matlab Dakshin',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 9, 'name' => 'Matlab Uttar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 9, 'name' => 'Shahrasti',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Anwara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Banshkhali',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Boalkhali',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Chandanaish',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Fatikchhari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Hathazari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Lohagara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Mirsharai',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Patiya',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Rangunia',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Raozan',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Sandwip',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Satkania',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Sitakunda',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Bandor (Chittagong Port) Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Chandgaon Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Double Mooring Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Kotwali Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Pahartali Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 10, 'name' => 'Panchlaish Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Barura',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Brahmanpara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Burichang',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Chandina',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Chauddagram',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Daudkandi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Debidwar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Homna',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Laksam',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Muradnagar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Nangalkot',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Comilla Adarsha Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Meghna',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Titas',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Monohargonj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 11, 'name' => 'Comilla Sadar Dakshin',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 12, 'name' => 'Chakaria',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 12, 'name' => "Cox's Bazar Sadar",  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 12, 'name' => 'Kutubdia',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 12, 'name' => 'Maheshkhali',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 12, 'name' => 'Ramu',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 12, 'name' => 'Teknaf',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 12, 'name' => 'Ukhia',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 12, 'name' => 'Pekua',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 13, 'name' => 'Chhagalnaiya',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 13, 'name' => 'Daganbhuiyan',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 13, 'name' => 'Feni Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 13, 'name' => 'Parshuram',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 13, 'name' => 'Sonagazi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 13, 'name' => 'Fulgazi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 14, 'name' => 'Dighinala',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 14, 'name' => 'Khagrachhari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 14, 'name' => 'Lakshmichhari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 14, 'name' => 'Mahalchhari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 14, 'name' => 'Manikchhari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 14, 'name' => 'Matiranga',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 14, 'name' => 'Panchhari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 14, 'name' => 'Ramgarh',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 15, 'name' => 'Lakshmipur Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 15, 'name' => 'Raipur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 15, 'name' => 'Ramganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 15, 'name' => 'Ramgati',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 15, 'name' => 'Kamalnagar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 16, 'name' => 'Begumganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 16, 'name' => 'Noakhali Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 16, 'name' => 'Chatkhil',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 16, 'name' => 'Companiganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 16, 'name' => 'Hatiya',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 16, 'name' => 'Senbagh',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 16, 'name' => 'Sonaimuri',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 16, 'name' => 'Subarnachar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 16, 'name' => 'Kabirhat',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 17, 'name' => 'Bagaichhari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 17, 'name' => 'Barkal',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 17, 'name' => 'Kawkhali (Betbunia)',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 17, 'name' => 'Belaichhari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 17, 'name' => 'Kaptai',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 17, 'name' => 'Juraichhari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 17, 'name' => 'Langadu',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 17, 'name' => 'Naniyachar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 17, 'name' => 'Rajasthali',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 17, 'name' => 'Rangamati Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Dhamrai',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Dohar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Keraniganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Nawabganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Savar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 19, 'name' => 'Alfadanga',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 19, 'name' => 'Bhanga',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 19, 'name' => 'Boalmari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 19, 'name' => 'Charbhadrasan',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 19, 'name' => 'Faridpur Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 19, 'name' => 'Madhukhali',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 19, 'name' => 'Nagarkanda',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 19, 'name' => 'Sadarpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 19, 'name' => 'Saltha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 20, 'name' => 'Gazipur Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 20, 'name' => 'Kaliakair',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 20, 'name' => 'Kaliganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 20, 'name' => 'Kapasia',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 20, 'name' => 'Sreepur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 21, 'name' => 'Gopalganj Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 21, 'name' => 'Kashiani',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 21, 'name' => 'Kotalipara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 21, 'name' => 'Muksudpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 21, 'name' => 'Tungipara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 22, 'name' => 'Baksiganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 22, 'name' => 'Dewanganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 22, 'name' => 'Islampur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 22, 'name' => 'Jamalpur Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 22, 'name' => 'Madarganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 22, 'name' => 'Melandaha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 22, 'name' => 'Sarishabari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 23, 'name' => 'Astagram',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 23, 'name' => 'Bajitpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 23, 'name' => 'Bhairab',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 23, 'name' => 'Hossainpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 23, 'name' => 'Itna',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 23, 'name' => 'Karimganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 23, 'name' => 'Katiadi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 23, 'name' => 'Kishoreganj Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 23, 'name' => 'Kuliarchar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 23, 'name' => 'Mithamain',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 23, 'name' => 'Nikli',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 23, 'name' => 'Pakundia',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 23, 'name' => 'Tarail',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 24, 'name' => 'Rajoir',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 24, 'name' => 'Madaripur Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 24, 'name' => 'Kalkini',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 24, 'name' => 'Shibchar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 25, 'name' => 'Daulatpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 25, 'name' => 'Ghior',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 25, 'name' => 'Harirampur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 25, 'name' => 'Manikgonj Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 25, 'name' => 'Saturia',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 25, 'name' => 'Shivalaya',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 25, 'name' => 'Singair',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 26, 'name' => 'Gazaria',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 26, 'name' => 'Lohajang',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 26, 'name' => 'Munshiganj Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 26, 'name' => 'Sirajdikhan',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 26, 'name' => 'Sreenagar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 26, 'name' => 'Tongibari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 27, 'name' => 'Bhaluka',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 27, 'name' => 'Dhobaura',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 27, 'name' => 'Fulbaria',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 27, 'name' => 'Gaffargaon',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 27, 'name' => 'Gauripur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 27, 'name' => 'Haluaghat',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 27, 'name' => 'Ishwarganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 27, 'name' => 'Mymensingh Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 27, 'name' => 'Muktagachha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 27, 'name' => 'Nandail',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 27, 'name' => 'Phulpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 27, 'name' => 'Trishal',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 27, 'name' => 'Tara Khanda',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 28, 'name' => 'Araihazar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 28, 'name' => 'Bandar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 28, 'name' => 'Narayanganj Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 28, 'name' => 'Rupganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 28, 'name' => 'Sonargaon',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 30, 'name' => 'Atpara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 30, 'name' => 'Barhatta',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 30, 'name' => 'Durgapur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 30, 'name' => 'Khaliajuri',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 30, 'name' => 'Kalmakanda',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 30, 'name' => 'Kendua',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 30, 'name' => 'Madan',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 30, 'name' => 'Mohanganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 30, 'name' => 'Netrokona Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 30, 'name' => 'Purbadhala',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 31, 'name' => 'Baliakandi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 31, 'name' => 'Goalandaghat',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 31, 'name' => 'Pangsha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 31, 'name' => 'Rajbari Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 31, 'name' => 'Kalukhali',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 32, 'name' => 'Bhedarganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 32, 'name' => 'Damudya',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 32, 'name' => 'Gosairhat',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 32, 'name' => 'Naria',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 32, 'name' => 'Shariatpur Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 32, 'name' => 'Zanjira',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 32, 'name' => 'Shakhipur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 33, 'name' => 'Jhenaigati',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 33, 'name' => 'Nakla',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 33, 'name' => 'Nalitabari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 33, 'name' => 'Sherpur Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 33, 'name' => 'Sreebardi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 34, 'name' => 'Gopalpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 34, 'name' => 'Basail',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 34, 'name' => 'Bhuapur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 34, 'name' => 'Delduar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 34, 'name' => 'Ghatail',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 34, 'name' => 'Kalihati',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 34, 'name' => 'Madhupur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 34, 'name' => 'Mirzapur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 34, 'name' => 'Nagarpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 34, 'name' => 'Sakhipur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 34, 'name' => 'Dhanbari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 34, 'name' => 'Tangail Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 29, 'name' => 'Narsingdi Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 29, 'name' => 'Belabo',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 29, 'name' => 'Monohardi',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 29, 'name' => 'Palash',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 29, 'name' => 'Raipura',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 29, 'name' => 'Shibpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 35, 'name' => 'Bagerhat Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 35, 'name' => 'Chitalmari',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 35, 'name' => 'Fakirhat',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 35, 'name' => 'Kachua',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 35, 'name' => 'Mollahat',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 35, 'name' => 'Mongla',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 35, 'name' => 'Morrelganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 35, 'name' => 'Rampal',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 35, 'name' => 'Sarankhola',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 36, 'name' => 'Alamdanga',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 36, 'name' => 'Chuadanga Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 36, 'name' => 'Damurhuda',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 36, 'name' => 'Jibannagar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 37, 'name' => 'Abhaynagar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 37, 'name' => 'Bagherpara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 37, 'name' => 'Chaugachha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 37, 'name' => 'Jhikargachha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 37, 'name' => 'Keshabpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 37, 'name' => 'Jessore Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 37, 'name' => 'Manirampur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 37, 'name' => 'Sharsha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 38, 'name' => 'Harinakunda',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 38, 'name' => 'Jhenaidah Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 38, 'name' => 'Kaliganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 38, 'name' => 'Kotchandpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 38, 'name' => 'Maheshpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 38, 'name' => 'Shailkupa',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Batiaghata',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Dacope',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Dumuria',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Dighalia',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Koyra',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Paikgachha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Phultala',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Rupsha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Terokhada',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Daulatpur Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Khalishpur Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Khan Jahan Ali Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Kotwali Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Sonadanga Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Harintana Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 40, 'name' => 'Bheramara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 40, 'name' => 'Daulatpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 40, 'name' => 'Khoksa',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 40, 'name' => 'Kumarkhali',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 40, 'name' => 'Kushtia Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 40, 'name' => 'Mirpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 40, 'name' => 'Shekhpara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 41, 'name' => 'Magura Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 41, 'name' => 'Mohammadpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 41, 'name' => 'Shalikha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 41, 'name' => 'Sreepur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 42, 'name' => 'Gangni',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 42, 'name' => 'Meherpur Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 42, 'name' => 'Mujibnagar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 43, 'name' => 'Kalia',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 43, 'name' => 'Lohagara',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 43, 'name' => 'Narail Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 43, 'name' => 'Naragati Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 44, 'name' => 'Assasuni',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 44, 'name' => 'Debhata',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 44, 'name' => 'Kalaroa',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 44, 'name' => 'Kaliganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 44, 'name' => 'Satkhira Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 44, 'name' => 'Shyamnagar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 44, 'name' => 'Tala',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 61, 'name' => 'Ajmiriganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 61, 'name' => 'Bahubal',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 61, 'name' => 'Baniyachong',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 61, 'name' => 'Chunarughat',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 61, 'name' => 'Habiganj Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 61, 'name' => 'Lakhai',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 61, 'name' => 'Madhabpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 61, 'name' => 'Nabiganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 62, 'name' => 'Barlekha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 62, 'name' => 'Kamalganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 62, 'name' => 'Kulaura',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 62, 'name' => 'Moulvibazar Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 62, 'name' => 'Rajnagar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 62, 'name' => 'Sreemangal',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 62, 'name' => 'Juri',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 63, 'name' => 'Bishwamvarpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 63, 'name' => 'Chhatak',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 63, 'name' => 'Derai',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 63, 'name' => 'Dharampasha',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 63, 'name' => 'Dowarabazar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 63, 'name' => 'Jagannathpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 63, 'name' => 'Jamalganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 63, 'name' => 'Sullah',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 63, 'name' => 'Sunamganj Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 63, 'name' => 'Tahirpur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 63, 'name' => 'South Sunamganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 64, 'name' => 'Balaganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 64, 'name' => 'Beanibazar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 64, 'name' => 'Bishwanath',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 64, 'name' => 'Companigonj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 64, 'name' => 'Fenchuganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 64, 'name' => 'Golapganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 64, 'name' => 'Gowainghat',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 64, 'name' => 'Jaintiapur',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 64, 'name' => 'Kanaighat',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 64, 'name' => 'Sylhet Sadar',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 64, 'name' => 'Zakiganj',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 64, 'name' => 'South Shurma',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Adabor Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Badda Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Bangsal Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Bimanbandar Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Cantonment Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Chak Bazar Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Dakshinkhan Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Darus Salam Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Demra Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Dhanmondi Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Gendaria Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Gulshan Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Hazaribagh Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Jatrabari Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Kadamtali Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Kafrul Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Kalabagan Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Kamrangirchar Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Khilgaon Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'khilkhet Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Kotwali Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Lalbagh Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Mirpur Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Mohammadpur Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Motijheel Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Newmarket Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Pallabi Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Paltan Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Ramna Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Rampura Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Sabujbagh Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Shah Ali Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Shahbag Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Sher-e-Bangla Nagar Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Shyampur Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Sutrapur Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Tejgaon Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Mohakhali Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Tejgaon Industrial Area Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Turag Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Uttara Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 18, 'name' => 'Uttar Khan Thana',  'created_at' => $now, 'updated_at' => $now],
            ['district_id' => 39, 'name' => 'Khulna Sadar',  'created_at' => $now, 'updated_at' => $now],
        ];

        collect($rows)->chunk(200)->each(function ($chunk) {
            DB::table('upazilas')->insert($chunk->all());
        });
    }
}
